### ISSUE TITLE
Cannot connect to Cassandra 3.7

### ISSUE THREAD

**Issue by orangemi** [gocql/gocql#782] opened 2016-09-13 07:15 UTC
- Start [Cassandra 3.7](http://www.apache.org/dyn/closer.lua/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz) with `bin/cassandra -f`
- Use the Example code written in `README` and change the host to `localhost`
Result:
```
2016/09/13 15:11:23 gocql: unable to dial control conn localhost:9042: gocql: error on stream 0: Invalid or unsupported protocol version (2); the lowest supported version is 3 and the greatest is 4
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xac656]

goroutine 1 [running]:
panic(0x20efc0, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gocql/gocql.(*Session).Close(0x0)
	/Users/Orange/projects/go/src/github.com/gocql/gocql/session.go:328 +0x26
panic(0x20efc0, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/gocql/gocql.(*Session).Query(0x0, 0x256495, 0x37, 0xc4200c40f0, 0x3, 0x3, 0xc84c8)
	/Users/Orange/projects/go/src/github.com/gocql/gocql/session.go:286 +0x26
main.main()
	/Users/Orange/projects/go/src/playground/cql1/main.go:25 +0x279
exit status 2
```

Note: No problem with Cassandra 2.2.7, but a warning:
```
WARN  06:48:32 Detected connection using native protocol version 2. Both version 1 and 2 of the native protocol are now deprecated and support will be removed in Cassandra 3.0. You are encouraged to upgrade to a client driver using version 3 of the native protocol
```

I saw README said to change the protocol version to use Cassandra 3 but how?

**Comment by orangemi** [comment] 2016-09-13 07:24
Sorry I'm very new to Go. I found the solution.
After `cluster := gocql.NewCluster("localhost")`, add `cluster.ProtoVersion = 3` to solve.
But it does not look good to use. Is there any plan to solve?

**Comment by orangemi** [comment] 2016-09-13 07:25
I think #691 said the same thing.

**Comment by Zariel** [comment] 2016-09-13 20:49
We should essentially implement auto detection of protocol see #540. Cassandra requires you to set a protocol version, the error is saying it must be 3 or 4 for version > 3. Set it to 4 and everything will be fine. Closing this a duplicate of #691

**Closed by Zariel** 2016-09-13 20:49 UTC
