### ISSUE TITLE
Batch queries failing 

### ISSUE THREAD

**Issue by xoraes** [gocql/gocql#364] opened 2015-04-15 08:00 UTC
Recently started seeing issues with gocql when performing batch updates to cassandra 2.1.3 in unloggedbatch mode. My guess it that this is somehow related to the changes made since 4/1/2015. 

sample batch update:
UPDATE counters.stats SET value = value + 1 WHERE id = '5' and type = 'd' and subtype = 's' and event = 'i'

where partition key is id and type,subtype,event are composite column keys.

server throws this error: Not enough bytes to read an UTF8 serialized string preceded by it's 4 bytes length.

From C* system.log :

ERROR [SharedPool-Worker-2] 2015-04-15 07:51:17,598 Message.java:538 - Unexpected exception during request; channel = [id: 0xcc6e6869, /172.27.132.28:59160 => /172.27.133.85:9042]
java.lang.IndexOutOfBoundsException: readerIndex(105) + length(4) exceeds writerIndex(105): SlicedByteBuf(ridx: 105, widx: 105, cap: 105/105, unwrapped: PooledUnsafeDirectByteBuf(ridx: 113, widx: 113, cap: 2048))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:619) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at org.apache.cassandra.transport.CBUtil.readValue(CBUtil.java:333) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at org.apache.cassandra.transport.CBUtil.readValueList(CBUtil.java:386) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at org.apache.cassandra.transport.messages.BatchMessage$1.decode(BatchMessage.java:64) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at org.apache.cassandra.transport.messages.BatchMessage$1.decode(BatchMessage.java:45) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at org.apache.cassandra.transport.Message$ProtocolDecoder.decode(Message.java:247) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at org.apache.cassandra.transport.Message$ProtocolDecoder.decode(Message.java:235) ~[apache-cassandra-2.1.3.jar:2.1.3]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]

**Comment by 0x6e6562** [comment] 2015-04-15 08:33
@xoraes This could well be due to #339, so it will be good to flush out any new bugs we may have introduced. Just so that we have a record of this, was this caused by upgrading an app that was previously working using gocql @ 180456f or earlier? In other words, were you to roll this upgrade back, does that make the symptom go away?

**Comment by xoraes** [comment] 2015-04-15 08:40
I have two environments, one running gocql from April 1st and another one more recent. Only the recent one is having this issue.

**Comment by 0x6e6562** [comment] 2015-04-15 08:48
>I have two environments, one running gocql from April 1st and another one more recent. Only the recent one is having this issue.

#339 was merged on 09/04/2015, so the master version from April 1st won't have had this particular bug in it. Thanks for confirming our suspicions.

**Closed** 2015-04-15 09:15 UTC

**Comment by 0x6e6562** [comment] 2015-04-15 09:16
I noticed that this ticket got auto-closed by the merge of the pull request - do let us know if you are still seeing this issue.
