### ISSUE TITLE
UDT not work with ScyllaDB 

### ISSUE THREAD

**Issue by slayercat** [gocql/gocql#757] opened 2016-07-26 12:08 UTC
Env:
ScyllaDB [https://github.com/scylladb/scylla] version `1.2.2`
gocql version `94f1315e46b0b2eae3a48a77a49e3e1cc9377923`

user following User Define Type
```
CREATE TYPE A.F (
	m   ascii,
	ft   ascii,	 
	fn  text,	 
	sz  bigint,
	td   ascii
);
```
and following Table
```

CREATE TABLE A.s (
  si  bigint PRIMARY KEY,
  ru                  frozen<A.F>,  
```

with the guide in `https://github.com/gocql/gocql/blob/master/udt_test.go`

I use the following method

```
import "fmt"
import "github.com/gocql/gocql"

type F struct {
	M      string `cql:"m"`
	Ft           string `cql:"ft"`
	Fn              string `cql:"fn"`
	Sz            uint64 `cql:"sz"`
	Td           string `cql:"td"`
}

func (p *F) MarshalUDT(name string, info gocql.TypeInfo) ([]byte, error) {
	switch name {
	case "m":
		return gocql.Marshal(info, p.M)
	case "ft":
		return gocql.Marshal(info, p.Ft)
	case "fn":
		return gocql.Marshal(info, p.Fn)
	case "sz":
		return gocql.Marshal(info, p.Sz)
	case "td":
		return gocql.Marshal(info, p.Td)
	default:
		return nil, fmt.Errorf("unknown column for position: %q", name)
	}
}

func (p *F) UnmarshalUDT(name string, info gocql.TypeInfo, data []byte) error {
	switch name {
	case "m":
		return gocql.Unmarshal(info, data, &p.M)
	case "ft":
		return gocql.Unmarshal(info, data, &p.Ft)
	case "fn":
		return gocql.Unmarshal(info, data, &p.Fn)
	case "sz":
		return gocql.Unmarshal(info, data, &p.Sz)
	case "td":
		return gocql.Unmarshal(info, data, &p.Td)
	default:
		return fmt.Errorf("unknown column for position: %q", name)
	}
}


s:=&F{}
err = session.Query(
		`SELECT 
				ru
				FROM A.s limit 1` ).Scan(s); 
```

But It came up err
```
panic: gocql: not enough columns to scan into: have 1 want 5

goroutine 1 [running]:
main.main()
	<PATH>.go:114 +0x272


```

a deep view digs out it came from `session.go:1053`. 

when remove these lines. It cameout the result's `col.TypeInfo.Type` is `TypeTuple`. Not expected `UDTTypeInfo`.  So I can't convert result to struct F.

I stucked here. any help is welcomed.

**Comment by penberg** [comment] 2016-07-26 13:53
@slayercat I am not able to reproduce the error with [this reproducer](https://gist.github.com/penberg/46617bc464d4688c20c7f6370f7e5b0e).

Are you sure you are using Scylla 1.2.2 and not some earlier version? I'm asking because the bug very similar to https://github.com/scylladb/scylla/issues/1443 which is fixed only in 1.2.2 and the upcoming 1.3 release.

@avikivity @duarten

**Comment by avikivity** [comment] 2016-07-26 13:59
This is https://github.com/scylladb/scylla/issues/1443.

**Comment by avikivity** [comment] 2016-07-26 14:01
@penberg 1484 is slated for 1.2.3, it's not in 1.2.2.

We should soonish.

**Comment by avikivity** [comment] 2016-07-26 14:02
Meanwhile, this bug can be closed, since it's not a gocql problem.

**Comment by avikivity** [comment] 2016-07-26 14:16
ignore my previous two comments (and this one too).

**Comment by penberg** [comment] 2016-07-26 14:16
@avikivity The CQL binary protocol UDT metadata fix _is_ in 1.2.2: http://www.scylladb.com/2016/07/21/release-1.2.2/

Like I said, I suspect @slayercat is using an older version and hitting the now fixed bug.

**Comment by slayercat** [comment] 2016-07-27 06:41
Thanks,@penberg @avikivity , and sorry for version misreport. I rechecked and find it's `version 1.2.0`. pulled on dockerhub.

I retried on `version 1.3.0 RC`. and it works when there's value. but won't work when the result is NULL. A  reproducer [here](https://gist.github.com/slayercat/d2820d46bfbd5f34424dacad4175443a])

The panic info here.
```
[root@localhost home]# go run a.go
2016/07/27 06:21:52 closing keyspace session
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/gocql/gocql.unmarshalUDT(0x7ffff7fbc380, 0xc208030c60, 0x0, 0x0, 0x0, 0x694f60, 0xc208094da0, 0x0, 0x0)
	/disk/GOPATH/src/github.com/gocql/gocql/marshal.go:1654 +0x574
github.com/gocql/gocql.Unmarshal(0x7ffff7fbc380, 0xc208030c60, 0x0, 0x0, 0x0, 0x694f60, 0xc208094da0, 0x0, 0x0)
	/disk/GOPATH/src/github.com/gocql/gocql/marshal.go:157 +0x9b7
github.com/gocql/gocql.(*Iter).Scan(0xc20806c630, 0xc20800adc0, 0x1, 0x1, 0x7ffff7fa9000)
	/disk/GOPATH/src/github.com/gocql/gocql/session.go:1084 +0x6ff
github.com/gocql/gocql.(*Query).Scan(0xc208082700, 0xc20800adc0, 0x1, 0x1, 0x0, 0x0)
	/disk/GOPATH/src/github.com/gocql/gocql/session.go:918 +0xab
main.main()
	/home/a.go:86 +0x4cd

goroutine 31 [runnable]:
net.(*pollDesc).Wait(0xc2080108b0, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080108b0, 0x0, 0x0)

```

Did some dig and found when there's a null UDT return, server will return a 0 length message. which will failed there.

Not sure if it's normal cassandra CQL protocol behavior.

Thanks again.

**Comment by penberg** [comment] 2016-07-27 06:56
@slayercat I am able to reproduce the null UDT issue with Cassandra 2.1.8 so it's likely a gocql problem.

**Comment by penberg** [comment] 2016-07-27 07:18
@slayercat Yup, I think it's a gocql UDT unmarshaling bug and sent a pull request to fix it up.

**Closed** 2016-07-28 08:33 UTC
