### ISSUE TITLE
Panic of gocql with TokenAwareHostPolicy and zero replication factor for a datacenter

### ISSUE THREAD

**Issue by antonio-tringali** [gocql/gocql#1501] opened 2020-10-15 14:57 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
Cassandra version 3.11.4

### What version of Gocql are you using?
v0.0.0-20200131111108-92af2e088537

### What did you do?
The test cluster is made up of three datacenters with three nodes each. Let's call them DC1, DC2 and DC3.

With an active client, connected to the cluster via TokenAwareHostPolicy, I created a new keyspace with:

CREATE KEYSPACE test_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3', 'DC2': '3', 'DC3': '0'} AND durable_writes = true;

i.e., keyspace DC3 has replication factor 0. The application panics with the following stacktrace:

```
panic: invalid replication_factor 0. Is the "rdrive_smule_ng:dc=DEN02" keyspace configured correctly?
goroutine 1907 [running]:
github.com/gocql/gocql.getReplicationFactorFromOpts(0xc000d27620, 0x18, 0x1656220, 0xc001aefb90, 0x4)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/topology.go:67 +0x2c2
github.com/gocql/gocql.getStrategy(0xc000d44460, 0xf, 0xc000d44460)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/topology.go:86 +0x1de
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc00047a000, 0xc001aefad0, 0xc001c18a50, 0xf)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/policies.go:455 +0x228
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc00047a000, 0xc001c18a50, 0xf, 0xc001c18a40, 0x7)
/go/pkg/mod/github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/policies.go:443 +0x99

```
### What did you expect to see?
Do not panic.

This procedure seems valid: [Updating the replication factor
](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useUpdateKeyspaceRF.html)

### What did you see instead?
I witnessed a panic.

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by vigliag** [comment] 2021-04-16 07:39
Hi, it seems this has been fixed by https://github.com/gocql/gocql/pull/1552 (thanks!), I cannot reproduce the above crash anymore

**Closed** 2021-04-16 13:11 UTC
