### ISSUE TITLE
Marshal/Unmarshal of struct fields of type []byte do not work for uuid cql type

### ISSUE THREAD

**Issue by sapiens-sapide** [gocql/gocql#868] opened 2017-03-09 14:55 UTC
Field of type `[]byte` that maps to an `uuid` type within Cassandra will failed to Marshal/Unmarshal with error `can not marshal []uint8 into uuid`.  
Likely because gocql's functions _marshalUUID_ and _unmarshalUUID_ test if the field is of type `[]byte`. But the go's `.(type)` switch returns a type `[]uint8` instead !  
The switch within _marshalUUID_ and _unmarshalUUID_ functions (and related) should have : 
```
case []uint8:
```

**Comment by papisz** [comment] 2017-04-01 22:11
Hi, is this a confirmed bug? I was looking for a "good first contribution", but I am unable to reproduce this one (perhaps I've made a mistake somewhere).

I've created a simple struct with `[]byte`, added some data with cassandra's `uuid` type and it works for me.

The *only way* I've managed to get the same error was passing *inproperly* casted uuid to `Marshal(NativeType{proto: 2, typ: TypeUUID}, u)`, like:

`u := []byte("1fe042e5-f5af-46ab-bc95-23c69d32d8f2") // bad, gives a 36 element byte array (and marshalUUID needs` [exactly 16](https://github.com/gocql/gocql/blob/5c85086f3f0274168bd732e03351f67a1b63f450/marshal.go#L1426))

instead of

```
uu, _ := ParseUUID("1fe042e5-f5af-46ab-bc95-23c69d32d8f2")
u := uu.Bytes() // good, gives a 16 element byte array
```

I've tried also (as suggested) adding `[]uint8` to `marshalUUID`/`unmarshalUUID` functions. But it just can't be done, Go complains about it:
```
duplicate case []uint8 in type switch previous case at ./marshal.go:1427
```

Perhaps because of [byte being an alias for uint8](http://stackoverflow.com/questions/22950392/difference-between-uint8-byte-golang-slices).

I'd be very happy to try to fix this, if you could point me in the right direction on how to reproduce this bug.

**Comment by Zariel** [comment] 2017-04-02 16:03
If it works then I would be happy to accept a PR that adds a test marshalling/unmarshalling using `[]uint8` and closing this issue. From my checking it seems that it should handle uint8 just fine.

**Comment by sapiens-sapide** [comment] 2017-04-03 12:34
I cannot reproduce the bug outside of my software… May be there is a name conflict within my stack. But, I still suggest to __replace__ the type switch case from `case []byte` to `case[]uint8`.
Regards.

**Comment by leighmcculloch** [comment] 2017-04-09 00:07
I think what @papisz is highlighting is on point: a `[]byte` and `[]uint8` are the same type and are interchangeable. Example: https://play.golang.org/p/XX8FjKFtOf.

@sapiens-sapide: The reason you see the error mentioning `[]uint8` is because if you print the type of a `[]byte` it will come out as `[]uint8`. Example: https://play.golang.org/p/tZtUtD12Bg.

As @papisz pointed out it's likely the `[]byte` you're attempting to marshal is not the correct length, because [the unmarshalUUID function](https://github.com/gocql/gocql/blob/ec709fa434721e313ec6c434aa1e0b0742e51cbd/marshal.go#L1425-L1441) will print the error you're seeing if the `[]byte` is not a length of `16`.

**Comment by Zariel** [comment] 2017-04-09 13:24
A fix for this then is to improve the error message when its not 16 bytes long

**Closed** 2017-04-09 15:58 UTC
Labels: good-first-contribution

**Comment by Zariel** [comment] 2017-04-09 21:52
Thanks @papisz  and @leighmcculloch for looking into this!
