### ISSUE TITLE
use of system.local rpc_address breaks gocql for rpc_address 0.0.0.0 configuration

### ISSUE THREAD

**Issue by liviosoares** [gocql/gocql#509] opened 2015-10-29 02:45 UTC
Commit a70d1ac9aaf9d1b373cbf3133893b9ff44f8cb33 changes strategy for retrieving IP information of nodes in a cassandra cluster. It uses the `rpc_address` information from the `system.local` table.

Unfortunately, a `rpc_address` is not ideal way of retrieving this information (information below is from http://docs.datastax.com/en/cassandra/2.2/cassandra/configuration/configCassandra_yaml.html)

1) It can be set to 0.0.0.0 to configure Cassandra to listen to all interfaces,

2) broadcast_rpc_address can be used as a mechanism to overwrite the advertised address for the node (even in cases where rpc_address is *not* set to 0.0.0.0).

According to the cassandra documentation, it seems like clients really should be looking at broadcast_rpc_address information:

```
(Default: unset)note RPC address to broadcast to drivers and other Cassandra nodes.
This cannot be set to 0.0.0.0. If blank, it is set to the value of the rpc_address or rpc_interface.
If rpc_address or rpc_interfaceis set to 0.0.0.0, this property must be set.
```

Now, I'm not quite sure if this information corresponds to the `broadcast_rpc` field in the `system.local` table or the `rpc_address` of the `system.peers`. But I can say that the current behavior defined broke our tests since in our deployment rpc_address is set to 0.0.0.0, causing the gocql client to break communications with the cluster after an initial fetch of the `system.local` table information.

**Comment by Zariel** [comment] 2015-10-29 14:36
Fixed by #508

**Comment by liviosoares** [comment] 2015-10-29 15:01
Please re-open the issue. I just tested the and am getting an infinite loop in trying to access address 0.0.0.0.

`checkSystemLocal` in `host_source.go` is still querying `system.local` table for `rpc_address`, which is potentially not the correct address for clients to use.

**Comment by Zariel** [comment] 2015-10-29 15:22
Sorry I miss read this

**Comment by liviosoares** [comment] 2015-10-29 15:32
For what it's worth this patch fixes the issue in our setup:
https://github.com/liviosoares/gocql/commit/7eb0e423a0be7c947c5aa85561b7a8cbc20e1496

Unfortunately, I'm not knowledgable about the different possible variations of cassandra configs to tell whether this is a robust fix.

**Comment by balboah** [comment] 2015-10-30 09:30
@liviosoares thanks for the hint, used it in my PR and it fixed the issue for me while testing locally where rpc_address was 0.0.0.0.

**Comment by balboah** [comment] 2015-10-30 09:30
Sounds like it's safe to assume it should work when reading the docs

**Comment by liviosoares** [comment] 2015-10-30 15:03
@moadqassem is letting me know that `broadcast_address` is not quite there in older Cassandra versions (his version is 2.1.5): 
https://github.com/liviosoares/gocql/commit/7eb0e423a0be7c947c5aa85561b7a8cbc20e1496#commitcomment-14095533

Maybe we should make sure we know what other official drivers are doing (Java?). It may be that multiple properties need to be checked before a authoritative IP can be had... :disappointed:

**Comment by Zariel** [comment] 2015-10-30 15:06
@liviosoares there should be a check that the column exists in system.local, this should solve that issue?

**Comment by moadqassem** [comment] 2015-10-30 15:15
exactly, there is a check but that doesn't mean the problem is completely solved, because if you have any timeout configuration you application will timeout(that's what made me find out about this problem anyway). about the rpc_address its inside the system.peers table not system.local as the query in the new driver says.

**Comment by Zariel** [comment] 2015-10-30 15:33
Im not sure what the rpc_address and the peer address respond to in the peers table as its not entirely obvious. This is what the java driver does, https://github.com/datastax/java-driver/blob/0f9d734e0cccf79556749778c56d6a00995a7aa1/driver-core/src/main/java/com/datastax/driver/core/ControlConnection.java#L413

**Closed** 2015-11-02 13:06 UTC
