### ISSUE TITLE
hotspot invalid prepared statements 

### ISSUE THREAD

**Issue by rizzi37** [gocql/gocql#1581] opened 2021-09-22 08:44 UTC
```go
func main() {
	cluster := gocql.NewCluster("127.0.0.1", )
	cluster.Keyspace = "pangu"
	session, _ := cluster.CreateSession()


	//{
	//	var id int
	//	session.Query("select id from bar where id = ?", 1).Scan(&id)
	//}

	var g sync.WaitGroup
	q := session.Query("select id from bar where id = ?")
	for i := 0; i < 10; i++ {
		g.Add(1)
		i:=i
		go func() {
			st := time.Now()
			defer g.Done()
			var id int
			q.Bind(i).Scan(&id)
			fmt.Println(id)
			fmt.Println(time.Since(st))
		}()
	}

	g.Wait()


}

```

- if prepared statements  not ready, in goroutine, every query will cost same time like 3ms
- if the prepared statements ready,  every query will cost 1ms

**Comment by martin-sucha** [comment] 2021-09-23 14:51
Hello @rizzi37 ,

gocql caches prepared statements, so if the prepared statement is not already in the cache, gocql must issue a request to the server to prepare the statement first. So it naturally takes more time.

Could you please add more information? It is not clear from the original post how the behaviour impacts your use case - whether you encounter this only after startup or during normal operations of a service, for example. I would expect that in a running service, the prepared statements are cached most of the time, so the caching should not be a problem.

What do you think needs to be changed?

**Comment by rizzi37** [comment] 2021-09-24 03:12
hi @martin-sucha,

if the prepared statement is not already in the cache, i test found happened when  parallel for the first execution exec (instead 'in' cql), the  prepared statement cache not worked. 

Is it possible to implement like the "singleflight" function to prepared statements cache.Maybe my thinking is wrong. Is the responsibility of the database. idk~

**Comment by martin-sucha** [comment] 2021-10-04 17:48
@rizzi37 so far it seems that everything works as intended here. It is normal that executing statements takes longer when the prepared statement cache is cold as the driver needs to wait for the statement to be prepared. We already have single flight mechanism in the cache. So I'm closing this.

Feel free to reopen if you think something remains unanswered.

**Closed by martin-sucha** 2021-10-04 17:48 UTC
Labels: question
