### ISSUE TITLE
createSession() error

### ISSUE THREAD

**Issue by iker92** [gocql/gocql#969] opened 2017-09-07 15:33 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.0.9

### What version of Gocql are you using?
just done go get 

### What did you do?

I'm trying to initialize cassandra connection, the exactly same code on another archLinux machine is working like expected, I'm receiving this error: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bc9ff]

go env:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build538680768=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"

go version:
 go1.8.3 linux/amd64

output of uname -a
Linux 4.9.44-1-MANJARO #1 SMP PREEMPT Thu Aug 17 08:23:52 UTC 2017 x86_64 GNU/Linux

### What did you see instead?

---

If you are having connectivy related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by iker92** [comment] 2017-09-07 15:37
output of uname -a 

Linux 4.9.44-1-MANJARO #1 SMP PREEMPT Thu Aug 17 08:23:52 UTC 2017 x86_64 GNU/Linux

**Comment by Zariel** [comment] 2017-09-07 15:46
Can you post the full panic stack trace place

**Comment by iker92** [comment] 2017-09-09 10:11
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/user/price-probe-go/cassandra.InitCassandraClient(0xc420055c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/src/github.com/user/price-probe-go/cassandra/cassandra.go:18 +0x119
main.main()
	/home/user/go/src/github.com/user/price-probe-go/server.go:26 +0x22a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bcbe1]

**Comment by Zariel** [comment] 2017-09-09 14:32
no, post the stack trace which was caused by the panic

**Comment by Zariel** [comment] 2017-09-27 21:50
@iker92 after you see

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bc9ff]

``` 

It will be followed by a stack trace, please post that stack trace so that I can see where the null pointer is not a stack trace which is caused by calling `debug.Stack()`

**Comment by martin-sucha** [comment] 2021-12-22 16:42
There is no actionable information in this issue. Closing. Please reopen and add the full stack trace if you can still reproduce.

**Closed by martin-sucha** 2021-12-22 16:42 UTC
Labels: waiting-for-info
