### ISSUE TITLE
Panic during network partition/outage

### ISSUE THREAD

**Issue by nemothekid** [gocql/gocql#512] opened 2015-10-30 19:55 UTC
When gocql losses its connection - it panics. Not 100% sure how to reproduce. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2425e6]

goroutine 81 [running]:
github.com/channelmeter/gocql.(*ringDescriber).GetHosts(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nimi/go/src/github.com/channelmeter/gocql/host_source.go:53 +0x10b6
github.com/channelmeter/gocql.(*ringDescriber).refreshRing(0x0)
	/Users/nimi/go/src/github.com/channelmeter/gocql/host_source.go:142 +0x33
github.com/channelmeter/gocql.(*controlConn).reconnect(0xc20891d180, 0x282d001)
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:107 +0x327
github.com/channelmeter/gocql.(*controlConn).heartBeat(0xc20891d180)
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:57 +0x186
created by github.com/channelmeter/gocql.createControlConn
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:29 +0x172
```

Which points to this line:
```
func (r *ringDescriber) GetHosts() (hosts []HostInfo, partitioner string, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
```

I could reproduce this on my local, but I guess it would happen during prod as well during a network outage.

1. Start my program and connect to gocql
2. Turn off my wifi
3. Wait 5 minutes
4. Turn wifi back on
5. Panic!

Reproducing the error:
```
[2015-10-30T12:51:59.776-07:00] [API] [cm_api.go:338] [INFO] Starting Server...
[2015-10-30T12:52:10.85-07:00] [API] [cm_api.go:99] [INFO] Completed 200 OK /v3/admin/active in 336.935801ms for [::1]:53852 [ms=336.93]
[2015-10-30T12:52:27.012-07:00] [API] [cm_api.go:99] [INFO] Completed 401 Unauthorized /v3/admin/active in 7.206191091s for [::1]:53861 [ms=7206.19]
[2015-10-30T12:52:32.774-07:00] [API] [messenger.go:148] [ERROR] Received stream error: kafka: error while consuming api/0: read tcp 10.129.196.48:9092: operation timed out
[2015-10-30T12:52:34.276-07:00] [API] [cm_api.go:58] [INFO] 2015/10/30 12:52:34 RingDescriber: unable to get ring topology: gocql: connection closed waiting for response
[2015-10-30T12:53:04.276-07:00] [API] [cm_api.go:58] [INFO] 2015/10/30 12:53:04 RingDescriber: unable to get ring topology: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2425e6]

goroutine 97 [running]:
github.com/channelmeter/gocql.(*ringDescriber).GetHosts(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nimi/go/src/github.com/channelmeter/gocql/host_source.go:53 +0x10b6
github.com/channelmeter/gocql.(*ringDescriber).refreshRing(0x0)
	/Users/nimi/go/src/github.com/channelmeter/gocql/host_source.go:142 +0x33
github.com/channelmeter/gocql.(*controlConn).reconnect(0xc209d53000, 0x282d201)
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:107 +0x327
github.com/channelmeter/gocql.(*controlConn).heartBeat(0xc209d53000)
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:57 +0x186
created by github.com/channelmeter/gocql.createControlConn
	/Users/nimi/go/src/github.com/channelmeter/gocql/control.go:29 +0x172
```

Latest revision

**Comment by Zariel** [comment] 2015-10-30 20:28
I think this is a duplicate of #510, or related.

**Comment by nemothekid** [comment] 2015-10-30 22:50
Not sure how this is related to #510, it seems in this case `hostSource` is `nil` on the `session` instance for instance, but I can't find any place where its assigned to nil.

**Comment by nemothekid** [comment] 2015-10-30 23:23
Its seems the issue occurs if there is a network error and you have `ClusterConfig.DiscoverHosts` set to false.

**Closed** 2015-10-31 00:07 UTC
