### ISSUE TITLE
(*Conn).executeQuery panics when Cassandra not healthy

### ISSUE THREAD

**Issue by zhixinwen** [gocql/gocql#1141] opened 2018-06-12 18:43 UTC
### What version of Gocql are you using?
09f0498f9ab5ca0267e3b451483a368648de2158
### What did you do?
Cassandra was unhealthy and had high latency, and gocql crashed.
Log:
```
goroutine 248 [running]:
.../vendor/github.com/gocql/gocql.(*Conn).executeQuery(0xc42086c460, 0xc59d34a900, 0x6533599404)
	/go/src/.../vendor/github.com/gocql/gocql/conn.go:806 +0x17e
.../vendor/github.com/gocql/gocql.(*Query).execute(0xc59d34a900, 0xc42086c460, 0x14a0f40)
	/go/src/.../vendor/github.com/gocql/gocql/session.go:763 +0x35
.../vendor/github.com/gocql/gocql.(*queryExecutor).executeQuery(0xc4207bc240, 0xf619e0, 0xc59d34a900, 0x9e100f, 0xc4f8fa99a0, 0x3)
	/go/src/.../vendor/github.com/gocql/gocql/query_executor.go:42 +0x1bb
.../vendor/github.com/gocql/gocql.(*Session).executeQuery(0xc42002cdc0, 0xc59d34a900, 0x0)
	/go/src/.../vendor/github.com/gocql/gocql/session.go:389 +0xb7
.../vendor/github.com/gocql/gocql.(*Query).Iter(0xc59d34a900, 0xc565bcc540)
	/go/src/.../vendor/github.com/gocql/gocql/session.go:934 +0xac
```

**Comment by Zariel** [comment] 2018-06-12 19:32
What caused the panic? segfault?

**Comment by zhixinwen** [comment] 2018-06-12 19:33
High memory usage due to nodetool repair.

**Comment by Zariel** [comment] 2018-06-12 19:36
Sorry, I meant the bit in the log that said `panic: XXXX` followed by the reason, eg SIGSEGV

**Comment by zhixinwen** [comment] 2018-06-22 19:34
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x99db0e]

**Comment by alourie** [comment] 2018-08-21 03:28
@zhixinwen do you still experience this problem? Is there any more information that you have about this, like what text preceded the `goroutine 248 [running]:` in the error log message above? Otherwise, it's hard to figure out what the root cause of this.

Thanks.

**Comment by zhixinwen** [comment] 2018-08-21 03:54
Sorry I do not have more info about this.
But I dont think context preceded the error log would help, and I do not have that now.

**Comment by alourie** [comment] 2018-10-19 06:32
I'm going to close this as we don't have enough information to rely on. Can reopen if needed.

**Closed by alourie** 2018-10-19 06:32 UTC
