### ISSUE TITLE
Unmarshalling struct with *gocql.UUID

### ISSUE THREAD

**Issue by corydoras** [gocql/gocql#321] opened 2015-03-09 04:58 UTC
Im not yet an expert in GO, so I am not sure if I am even understanding this correctly yet, but it appears to me that when you have a struct like:

	type Sample struct {
	    Uuid *gocql.UUID,
	    Name string,
	}

Unmarshalling it to JSON fails to output the UUID, i.e. something like:

	i := &Sample{UUID: u, Name: "My name"}
	o, _ := json.Marshal(i)
	fmt.Println(string(o))

Am I missing something obvious, is it not possible to unmarshal like this?

**Comment by Zariel** [comment] 2015-03-09 15:03
I cant reproduce this with this test,

```go
func TestUUIDJsonPackage(t *testing.T) {
	uuid, err := ParseUUID("afa6c782-c66c-11e4-8e81-542696d74361")
	if err != nil {
		t.Fatal(err)
	}

	type testStruct struct {
		UUID *UUID
	}

	s := &testStruct{
		UUID: &uuid,
	}

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(s); err != nil {
		t.Fatal(err)
	}

	s = &testStruct{}

	log.Println(buf.String())

	if err := json.NewDecoder(&buf).Decode(s); err != nil {
		t.Fatal(err)
	}

	if s.UUID == nil {
		t.Fatal("UUID was not unmarshalled")
	}

	if uuid != *s.UUID {
		t.Fatalf("invalid uuid unmarshalling: got %v expected %v", s.UUID, &uuid)
	}
}
```

**Comment by Zariel** [comment] 2015-03-17 21:01
As there has been no followup im closing this, feel free to reopen this if this an issue.

**Closed by Zariel** 2015-03-17 21:01 UTC
Labels: question
