### ISSUE TITLE
Add ability to collect statistics

### ISSUE THREAD

**Issue by nyanshak** [gocql/gocql#992] opened 2017-10-23 18:25 UTC
I'd like to add the ability to send stats (to Datadog, statsd, or whatever) through an [xstats.XStater interface ](https://github.com/rs/xstats/blob/c67367528e160e557423e4d87059614d8c31a582/xstats.go#L41).

Right now, we're running several services using gocql connecting to a managed C* instance. This doesn't give us the visibility into certain stats that we'd like, and even if it did, it wouldn't be super-easy to break it down by WHICH service is having problems.

I'd like to add an option to send stats via an XStater interface. Right now, the biggest needs would be incrementing counters whenever connection states are changed (connection opened, connection closed, etc.). Lower priority would be adding stats around things such as latency (TTFB, etc).

@Zariel - I wanted to reach out with this issue to see if this idea is acceptable for the project and if any of the maintainers might be interested in taking this on. I'd be willing to try and help, but I'm not super experienced with the gocql code so I might need some pointers.

Thank you!
:)

**Comment by nyanshak** [comment] 2017-10-30 20:57
I went ahead and made https://github.com/gocql/gocql/pull/1010 as an example of what I'd like to do. Would love to get some feedback on the general approach as well as some agreement on good stat names.

**Comment by jacobgreenleaf** [comment] 2018-02-08 02:20
#1023 looks to be a more generic solution to this problem, and we like the general approach, but there are a lot of things that remain unmeasured after that change. Here are the metrics we think through experience will be useful for users of gocql:

**Connection pool instrumentation**. The logic around when the driver decides to start and stop connections in the pool ("fill" in the code) and how the driver chooses a particular connection in the connection pool is complex and needs more observability. We have observed numerous concerning bugs like #915 that cannot be analyzed without these metrics. Specifically:

* TCP Connection dialed (counter, result, timing)
* Protocol negotiated (counter, result, timing)
* Utilization of the in-use streams (gauge)
* Saturation (`IDGenerator.inuseStreams` gauge). In gocql case this pool cannot be saturated and in fact [emits an error](https://github.com/gocql/gocql/blob/58b3c7120a7ef9a077e4d089dd1badcb9ec756a8/internal/streams/streams.go#L75) rather than block for new stream. 

**Internal cache instrumentation**. The driver has a number of internal caches like the prepared statement LRU cache, routing key cache, and keyspace metadata. Specifically:

* Hit rate (counter, gauge)
* Cache size (gauge)
* Evictions (counter)

**Per-query and per-frame instrumentation**. This is a broad area that breaks down the work that the driver is doing to process individual query responses. How much time is spent decompressing? How much time is spent reading body rather than header? How many pages did this response require? How many rows did this query respond with? How long from flushing the query to the network until the first byte of the first frame? #1023 includes the last query and some timing information but it needs to be carefully separated the time spent decoding the frame header and time spent waiting for the body. In our experience a lot of query slowness is due to fat query bodies or high number of pages, but sometimes not, and this breakdown will help us root cause slow queries on the client side when the server side is "fine". Specifically:

* [Query] Throughput (counter)
* [Query] Row count, column count (gauge)
* [Query] Time to first byte (timing)
* [Query] Error rate (server-side like coordinator timeout, client-side) (counter)
* [Query] Frame count (derived at the end when receiving a frame with `Has_more_pages`)
* [Frame] Time spent waiting for bytes over the network. (timing)
* [Frame] Total time spent to read and decode frame body. (timing)
* [Frame] Body size pre and post compression (gauge)

**Server events**. This is the other side of #915 where it is hypothesized that the driver did not get events like topology changes. Internally we have experienced situations where the gocql driver will require a restart after the topology changes but without instrumentation of these events it is impossible to know why. Specifically:

* New node (counter)
* Removed node (counter)
* Status change (counter)
* Schema change (counter)

These metrics will help us tune (globally and on a per-query basis):

* Hard-coded values like [`TimeoutLimit`](https://github.com/gocql/gocql/blob/3688d5fd49d899f49773e1e5c7250d4cf3486d54/conn.go#L120), [`eventBufferSize`](https://github.com/gocql/gocql/blob/6ea202487e1a5ea51d627dfd681d24aaa31759ab/events.go#L51-L52)
* User-configurable values like [`ReconnectInterval`](https://github.com/gocql/gocql/blob/2f405b2923c93e24666d2317995803eefc6ba1e1/cluster.go#L69), [`Timeout`](https://github.com/gocql/gocql/blob/2f405b2923c93e24666d2317995803eefc6ba1e1/cluster.go#L48), `ConnectTimeout`, [`PageSize`](https://github.com/gocql/gocql/blob/2f405b2923c93e24666d2317995803eefc6ba1e1/cluster.go#L60)

Our goal with these metrics is for a system administrator to be able to root cause these common issues like query returning too many results, query too expensive, connection pool too saturated, reconnect interval too short, etc. from standardized metrics across many different query patterns, traffic load levels, network topologies, etc. and these should be in addition to server side metrics for maximum visibility. 

I have a patch that adds some of these metrics that I will send soon.

**Comment by alourie** [comment] 2019-04-05 07:11
@nyanshak I believe that with the addition of the Query/Batch observers as in #1023, this can now be solved as an external implementation of an Observer that writes to stat collector services (files, logs, datadog or whatever). Please let us know if you think it's not sufficient enough.

Thanks!

**Comment by martin-sucha** [comment] 2021-12-22 17:13
Query/Batch observers and other observers should provide enough information for the user to collect statistics about queries. You can monitor opening of connections with ConnectObserver. The only other thing mentioned in this issue that is missing seems to be DisconnectObserver, which would be issue #756. Closing in favor of that issue. Please let us know in case there are other things that you need to be monitored.

**Closed by martin-sucha** 2021-12-22 17:13 UTC
Labels: waiting-for-info
