### ISSUE TITLE
No prepared statement with ID X found

### ISSUE THREAD

**Issue by eliaslevy** [gocql/gocql#1252] opened 2019-01-07 23:17 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?

Scylla 2.3.1

### What version of Gocql are you using?

9de8c0414fd7ff72ee819f25a66e4942cb223873

### What did you do?

Data load into Scylla using INSERTs and UPDATEs via worker using parallel goroutines sharing a single gocql session.  All queries are marked as idempotent and are using `.WithTimestamp`.

Basic call structure is
```go
q := session.Query(statement, ...).
	WithTimestamp(microsecs).
	Idempotent(true)

if err := q(); err != nil {
	panic(err)
}
q.Release()
```

### What did you expect to see?

No errors.

### What did you see instead?

After running for nearly two hours the worker died after receiving a `No prepared statement with ID 5d348ed0f8b4217b44b5bfca8b70fc2f found` error.  Reading #152 I gather that this is an error that gocql should have been able to recover from, but it did not for some reason.

Looking a [the code handling the error](https://github.com/gocql/gocql/blob/70385f88b28b43805bd83d212169ab2d38810b15/conn.go#L1119-L1120), it seems that gocql will only try to reexecute the query if it successfully finds and removes the statement in its local statement cache.  The local cache is a LRU cache, which means that if the statement has fallen off the cache while the query is in flight, gocql may fail to reexecute the query resulting in the observed error.

The default cache size is 1,000.  It seems unlikely that the local statement cache was overflowed.  At the time of error the worker was executing ~25K inserts/updates per second, but the worker is using only 19 prepared statements (all with placeholders).  

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by syhlion** [comment] 2019-04-02 08:37
I have same problem too

**Comment by lppsuixn** [comment] 2019-05-06 07:50
same problem too

**Comment by ehsannm** [comment] 2019-07-15 03:21
we have the same issue, and this is still open

**Comment by Somebi** [comment] 2019-09-13 13:30
bump, same here

**Comment by alourie** [comment] 2019-09-13 13:52
I might be able to have another look in a few days. Sorry, folks, can't get to it sooner.

**Comment by mediocregopher** [comment] 2019-12-06 20:08
We are seeing this as well, on Scylla 3.1.1 and gocql `ae2f7fc85f32`. We have a 3 node cluster and only 2 queries being performed, so it would seem that queries are being pushed out of the prepared statement cache for some reason.

**Comment by mediocregopher** [comment] 2019-12-06 20:13
Would it be possible that if two connections received back `RequestErrUnprepared` at the same time the first one would remove the statement from the cache, but then before it retried it the other connection would look in the cache and see that it's not there anymore and return the error?

**Comment by dahankzter** [comment] 2019-12-09 10:26
This seems to be what the driver does @mediocregopher or am I misunderstanding what you mean?
If two connections get this error from the server it will only retry the operation for one that is "first".

This seems to be wrong. Shouldn't both connections try again? This is just the same scenario as a completely cold cache so it should not be a problem afaict.

What do you think @alourie ?

**Comment by dahankzter** [comment] 2019-12-09 11:20
Perhaps you could try to update your driver and Scylla @eliaslevy? I know it can be cumbersome and take some time but usually the newer the better. ;)

**Comment by alourie** [comment] 2019-12-09 11:52
@dahankzter I'm with you on this one. I don't see why missing a statement in the cache should ever return an error.

**Comment by dahankzter** [comment] 2019-12-09 15:02
There is a race here I guess but removing the check here won't change that. I mean since the removal happens outside and no "double check" is performed. Maybe it's not needed and a few manual retries would fix it either way @alourie.
It is possible for concurrent requests of the same statement to be reordered in such a way that the a newly created prepared statement gets evicted but that should only lead to a preparing a new one.
Not optimal but also no problem I would say.

**Comment by mediocregopher** [comment] 2019-12-09 16:19
> This seems to be what the driver does @mediocregopher or am I misunderstanding what you mean? If two connections get this error from the server it will only retry the operation for one that is "first".

Right, that's what I was pointing out as being a possible source of the bug, obviously that's not the intended behavior.

**Comment by dahankzter** [comment] 2019-12-09 17:00
This PR is the simplest possible fix for this although it would be good to get some more thoughts on this in case it's just too trivial @alourie.

**Comment by eliaslevy** [comment] 2019-12-09 20:23
@dahankzter alas, I've moved on and working on things non-Scylla related for the foreseeable future.

**Comment by dahankzter** [comment] 2019-12-11 09:20
No problem @eliaslevy good luck in your non-scylla stuff! :) You are welcome back any time!

**Closed** 2020-01-03 01:43 UTC
