### ISSUE TITLE
Cannot connect to scylla (Cassandra 2.2.8)

### ISSUE THREAD

**Issue by Ashtonian** [gocql/gocql#987] opened 2017-10-05 21:40 UTC
### What version of Cassandra are you using?
cqlsh 5.0.1 | Cassandra 2.2.8 | CQL spec 3.3.1 | Native protocol v4 | Scylla version 1.7.4-0.20170726.ff643e3

### What version of Gocql are you using?
Revision ce5020aabae349deda77bc1d559ef2300d3c93c5 

### What did you do?
use the following to spin up a local dev scylla instance  
```docker
docker run --name some-scylla -p 9042:9042 -d scylladb/scylla --broadcast-address 127.0.0.1 --broadcast-rpc-address 127.0.0.1  
```
and then ran 

```go
package main

import (
	"fmt"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	_, err := cluster.CreateSession()
	if err != nil {
		panic(err)
	}
	fmt.Println("cassandra init done")
}

```
### What did you expect to see?
Everything connect and initialize correctly. 

### What did you see instead?
```Cassandra Configuration failed: no connections were made when creating the session``` 

### Describe your Cassandra cluster
- output of `nodetool status`
```
[root@f779e8aea5c1 /]# nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  130.21 KB  256          ?       35a9b2db-a040-47bc-90b8-cdc6a56a17a6  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
``` 
- output of `SELECT peer, rpc_address FROM system.peers`
```
 peer | rpc_address
------+-------------
```
- rebuild your application with the `gocql_debug` tag and post the output
```
2017/10/05 16:38:18 gocql: Session.handleNodeUp: 127.0.0.1:9042
2017/10/05 16:38:20 unable to dial "172.17.0.2": dial tcp 172.17.0.2:9042: i/o timeout
2017/10/05 16:38:20 gocql: Session.handleNodeDown: 172.17.0.2:9042
2017/10/05 16:38:20 gocql: Session.handleNodeUp: 172.17.0.2:9042
2017/10/05 16:38:22 unable to dial "172.17.0.2": dial tcp 172.17.0.2:9042: i/o timeout
panic: no connections were made when creating the session
```

Related: https://github.com/gocql/gocql/issues/946

**Comment by Zariel** [comment] 2017-10-05 21:52
instead of setting broadcast to localhost set it to the address that docker is listening on, which in this case is 172.17.0.2

**Comment by Ashtonian** [comment] 2017-10-05 22:13
thanks for the quick response!

like this ? 
``` 
docker run --name some-scylla -p 9042:9042 -d scylladb/scylla --broadcast-rpc-address 172.17.0.2  --broadcast-address 172.17.0.2 
``` 

same output as before, is it intended that gocql tried to hit 172.17.0.2  when the broadcast address was set to localhost? I think that IP is an internal docker network ip thats not routable which is the problem. Which is why I thought setting the broadcast ip to localhost would tell gocql not to use 172.17.0.2 but rather localhost.

**Comment by penberg** [comment] 2017-10-06 05:12
Interestingly enough, the test program does not fail when I run it. That said, I think gocql is picking up the Docker IP from `--rpc-address` configuration option (from `system.local` table's `rpc_address` column), which Scylla Docker image defaults to host IP address:

https://github.com/scylladb/scylla/blob/master/dist/docker/redhat/scyllasetup.py#L59

**Comment by Ashtonian** [comment] 2017-10-06 16:24
@penberg thanks for looking into it - do you have the latest revision of the gocql driver? 

I just tried 
```
docker run --name some-scylla -p 9042:9042 -d scylladb/scylla --broadcast-address 127.0.0.1 --broadcast-rpc-address 127.0.0.1  --listen-address 127.0.0.1
```
I think the `--listen-address` is the same as `--rpc-address` and there is no `--rpc-address`
flag but I'm in the dark here, so I have no idea. That returned `panic: gocql: unable to create session: unable to discover protocol version: EOF`.

**Comment by penberg** [comment] 2017-10-09 11:07
@Ashtonian Yes, I was running with the latest revision of gocql.

I don't think you should change ``--listen-address`` to ``127.0.0.1`` because that makes Scylla bind to the container loopback device, which is not visible from the host.

Looking at the gocql error message more closely, you can clearly see that there's a node up event for `127.0.0.1` but you _also_ see a node up event for `172.17.0.2`. I am not sure why that happens for you and not for me. @Zariel, what are the different cases where `handleNodeUp` is called on? I don't think the IP address is coming from CQL events because there should be a `dispatching event` log line somewhere if we're in `handleNodeEvent`. The other two places are `setupConn` when setting up the control connection and `Session.init()` which does session initialization.

@Ashtonian One thing you could do here is fire up Wireshark that has a CQL protocol dissector and see if you're able to catch where that IP address is coming from.

**Comment by Zariel** [comment] 2017-10-09 18:01
broadcast address should be an address which the node is reachable on, so here it should be `172.17.0.2` but it appears that the node isn't reachable on this address as the dial just times out.

The events are coming from session init after discovering the ring it marks all hosts as up to add them to the connection pools.

Ill try and replicate

**Comment by pnordahl** [comment] 2017-10-09 20:31
I've been having the same issue. I was pinned to 7e9748c (~2 months ago) for this very reason. Unfortunately, I need fixes from b581ab4 and would prefer not to fork or cherry-pick to get there.

**Comment by penberg** [comment] 2017-10-10 11:48
@Zariel I think in this setup `172.17.0.2` is Docker-internal IP and _not_ reachable from the host. That's why @Ashtonian is setting broadcast address to `127.0.0.1` and using port forwarding as seen in the `docker run` command. That's why I don't understand where and why gocql is picking up that Docker-internal IP.

**Comment by maps90** [comment] 2017-10-11 06:33
I'm getting the same issue, if i'm using proxy to connect to cassandra. somehow i need to revert to 7e9748c to get it worked

2017/10/06 19:03:11 gocql: Session.handleNodeUp: 127.0.0.1:9042
2017/10/06 19:03:13 unable to dial "192.168.1.151": dial tcp 192.168.1.151:9042: i/o timeout
2017/10/06 19:03:13 gocql: Session.handleNodeDown: 192.168.1.151:9042
2017/10/06 19:03:15 unable to dial "192.168.1.150": dial tcp 192.168.1.150:9042: i/o timeout
2017/10/06 19:03:15 gocql: Session.handleNodeDown: 192.168.1.150:9042
2017/10/06 19:03:15 gocql: Session.handleNodeUp: 192.168.1.151:9042
2017/10/06 19:03:17 unable to dial "192.168.1.151": dial tcp 192.168.1.151:9042: i/o timeout
2017/10/06 19:03:17 gocql: Session.handleNodeDown: 192.168.1.151:9042
2017/10/06 19:03:17 gocql: Session.handleNodeUp: 192.168.1.150:9042
2017/10/06 19:03:19 unable to dial "192.168.1.150": dial tcp 192.168.1.150:9042: i/o timeout
2017/10/06 19:03:19 gocql: Session.handleNodeDown: 192.168.1.150:9042
2017/10/06 19:03:19 cassandra DB Connection Error:  no connections were made when creating the session

**Comment by Ashtonian** [comment] 2017-10-12 22:14
I was able to fix this by having Scylla bind to all ports internally. Not sure what that means for related parties, but I think its a mac os docker networking issue with the scylla instance. 

```docker
docker run --name some-scylla -p 9042:9042 -d scylladb/scylla --broadcast-address 127.0.0.1 --listen-address 0.0.0.0 --broadcast-rpc-address 127.0.0.1
```

**Comment by docmerlin** [comment] 2017-10-17 20:02
We are running into this problem any time we try to connect through a proxy or port forwarding.  Downgrading to hash 88748c7b290d13b288055f5dea4d1c49d44db06d of gocql fixed this issue for us, but it means we cannot use master.

**Comment by Ashtonian** [comment] 2017-10-17 20:40
I've also run into this now when trying to port forward to prod env. Have to VPN in...

**Comment by docmerlin** [comment] 2017-10-17 21:34
To clarify we don't just run into this with Scylla but with any Cassandra we need to connect to via port forwarding.

**Comment by Zariel** [comment] 2017-10-18 08:35
@Ashtonian @docmerlin could one of you open a new issue and describe the setup please?

**Comment by Zariel** [comment] 2017-10-19 17:59
This is incredibly hard to debug, solve and provably say that the issue is resolved because I can not replicate everyones different network conditions. I greatly simplified the host discovery code in #989 which should remove the issue that @penberg noticed about the rogue IP appearing, which is caused by using the remote TCP addr of the control connection as a valid host.

**Comment by Zariel** [comment] 2017-10-24 18:54
I think with #993 this should be fixed

**Comment by Zariel** [comment] 2017-10-25 20:45
if this is still an issue please reopen

**Closed by Zariel** 2017-10-25 20:45 UTC

**Comment by bzz** [comment] 2017-11-14 18:36
Stumbled up on this issue

With
```
docker run -p 9042:9042  --name scylla -d scylladb/scylla:2.0.0
go run connect.go
```

from issue description results in 

```
panic: no connections were made when creating the session

goroutine 1 [running]:
main.main()
	/xxx/connect.go:13 +0x12b
exit status 2
```

**Comment by awalga** [comment] 2019-01-26 10:58
I had the same issue and fixed it by creating a docker network and adding a virtual interface to the host. The solution does not need to override or user default rout (0.0.0.0) for listen, broadcast and broadcast-rpc.

# add a virtual interface (os x)
sudo ifconfig en0 inet 192.18.0.2 netmask 255.255.255.0 alias

# windows
ifconfig eth0:1 10.0.0.11 netmask 255.255.255.0 up

#create docker subnetwork
docker network create --subnet=192.18.0.0/24 skynet

#docker run scylla (you can always specify another ip for listen-address which need to be mapped to an alias on the host)

docker run --net skynet --ip 192.18.0.2 --name $NAME -p 192.18.0.2:9042:9042 -p 192.18.0.2:9160:9160 -d scylladb/scylla --overprovisioned 1

Clients will connect to the new adresse 192.18.0.2   i/o localhost

For those wondering where does 172.x.x.x come from, at startup scylla daemon creates system.local table and register container ip-address as listen-address(same for braodcast and broadcast-rpc). Clients retrieve those routes using cql and configure rpc (thrift to use those routes). if clients is containerized no issue as routing is handling by docker. But if clients is not containerized (eg client running on host) then it dials 172.x.x.x which does not exist on the host. I had this issue using scylladb with hadoop-gremlin for a janusgraph instance. Running a SparkGraphComputer fails.
