### ISSUE TITLE
Map cassandra port number in docker container from 9042 to 19042, connect fails

### ISSUE THREAD

**Issue by flei2000** [gocql/gocql#603] opened 2016-01-18 10:15 UTC
Start cassandra in a docker container and map the port number from 9042 inside to 19042 outside. Then cluster.CreateSession() fails with error message:
`no connections were made when creating the session`
But if I change the port number of cassandra in the container to 19042 and map it to 19042 outside, it succeeds.

**Comment by Zariel** [comment] 2016-01-18 10:32
What address are you using to dial?

**Comment by flei2000** [comment] 2016-01-18 12:02
localhost. I bind 0.0.0.0:19042->9042. `cqlsh localhost 10942` works but `gocql` does not. I'm using Ubuntu 14.04, cassandra 2.2.4 and docker image `cassandra:2.2.4`/

**Comment by Zariel** [comment] 2016-01-22 14:08
This is a duplicate of #575, I guess I need to update the readme to indicate that when cassandras internal port does not match its external port the config needs to disable inital host lookup.

**Closed by Zariel** 2016-01-22 14:08 UTC
