### ISSUE TITLE
"Memory leak" in exec(*Conn) time.NewTimer()

### ISSUE THREAD

**Issue by yuekui2** [gocql/gocql#851] opened 2017-01-16 18:57 UTC
We recently found there is significant resident memory increase in our service. We did profiling using pprof, which shows ~65% inuse space is from time.NewTimer(). 

Not sure how could I post the profiling results here. I could email it as needed.

Thanks.
-Kui

**Comment by Zariel** [comment] 2017-01-17 10:50
Thats interesting, you could email me the results and ill take a look

**Comment by yuekui2** [comment] 2017-01-17 18:54
Hi Chris,

See attached. In residentMem, we intentionally stopped the query traffic
for ~20 minutes to let gc kicked in, so that we could get a sense the "net"
memory usage.

Thanks for your help.

-Kui

**Comment by t2y** [comment] 2017-01-19 07:13
I'm interested in this issue, then reading conn.go now. I found that it seems not to close `call.timeout` channel in case `<-c.quit`. 

```go
close(call.timeout)
```
* https://github.com/gocql/gocql/blob/master/conn.go#L656

Additionally, there is an error case after that, and it seems not to close `call.timeout` channel.

* https://github.com/gocql/gocql/blob/master/conn.go#L668

I'm not sure whether `call.timeout` has already closed in those cases. Are those related to this issue?

**Comment by Zariel** [comment] 2017-01-19 09:05
@yuekui2 it looks like the attachment was removed?

**Comment by yuekui2** [comment] 2017-01-19 18:45
@Zariel Upload the attachment to google driver (see the link below)
We actually found the cause, which is due to a wrong timeout setting (10^6 seconds, as a result of switching a config to time.Duration). However, how does this mistake trigger the issue is still out of my mind. It seems this triggers some "weak" logic somewhere.

Thanks.

https://drive.google.com/open?id=0B1gwKAT7eAiPeHpQTHpqNkQzVzg
https://drive.google.com/open?id=0B1gwKAT7eAiPQ0NsNy1aMWpheVk
https://drive.google.com/open?id=0B1gwKAT7eAiPZ2VQRE5kcHY5SnM
https://drive.google.com/open?id=0B1gwKAT7eAiPZ21fSXhXQ2hwYlk

**Comment by yuekui2** [comment] 2017-01-19 19:09
@t2y 
I did try to figure out how many callReq objects are not going through the release code path. I revised the code to add an id to the callReq and give a sequential id in the New func of sync.pool. I record down the id and the timestamp when getting and releasing. https://drive.google.com/open?id=0B1gwKAT7eAiPRlIyWXN0QkhPOTg has the 2000 records from the beginning of the run. From the data, there is several not released. Still this should not cause the "leak", as I also measured the map size of conn.calls, which is around 40~50 during the entire (hours-level) run.

**Comment by Zariel** [comment] 2017-01-19 19:39
Not all `callReq` structs will be re used as the pool will be flushed between gc cycles so that I would expect. 

I guess the issue is that if a timeout is set and the call returns before the timeout the timer will still be running and is only stopped when it is pulled out of the pool.

**Comment by yuekui2** [comment] 2017-01-19 19:55
@Zariel 
1) as the id is assigned when New in sync pool, it should be at lease once, one get and one release. That is why this experiment emphasizes from the beginning of the run. My intention is just to get a sense of the number of requests are in some kind of "error" condition (, and the conclusion is very few)

2) even if the timer does not stop, it should NOT impact that it is GCed. I did an experiment (go code, https://drive.google.com/open?id=0B1gwKAT7eAiPT3BfcjgzU3RCRk0), simulating the logic how exec() using the timer, with the wrong "forever" timeout. When I ran it, no memory keeping increasing observed. So I suspect, somehow gocql code holds those timer somehow.

**Comment by yuekui2** [comment] 2017-01-21 01:15
Now I have a clear idea about how the long timeout causing "memory leak". Basically a timer object can NOT be garbage-collected before the timer expires. As the objects in the sync pool are moved to be garbage collected at the start time of every garbage collection cycles (see this link for sync pool, https://www.cockroachlabs.com/blog/how-to-optimize-garbage-collection-in-go/), for timers with long timeout,  they end up "holding" the memory before expiration, after moved to garbage collected from pool. 

The fix is actually straightforward, stop the timer before putting back to pool. I forked the repo and pushed a fix (commit b8c2d4b). This is my first to contribute on github. Not sure what is the next step.

Thanks.

**Comment by Zariel** [comment] 2017-01-21 13:50
@yuekui2 thank you very much! I have created a PR to add your commit and will merge once it passes CI

**Closed** 2017-01-22 11:54 UTC
Labels: in-progress
