### ISSUE TITLE
can not marshal float64 into bigint when storing float64 into DOUBLE column

### ISSUE THREAD

**Issue by Ekliptor** [gocql/gocql#1383] opened 2019-12-18 13:57 UTC
### What version of Cassandra are you using?
yugabyte-2.0.8.0 with:
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]

### What version of Gocql are you using?
github.com/yugabyte/gocql v0.0.0-20190522232832-e049977574e9

### What did you do?
I try to store Go float64 values in a DOUBLE column. Minimal sample file:
```
package main

/**
output:
2019/12/18 20:20:37 connected to cluster
2019/12/18 20:20:38 Created table test_float.accounts
2019/12/18 20:20:38 can not marshal float64 into bigint <- why does this happen?

yugabyte-2.0.8.0 with:
[cqlsh 5.0.1 | Cassandra 3.9-SNAPSHOT | CQL spec 3.4.2 | Native protocol v4]
*/

import (
	"github.com/yugabyte/gocql"
	"log"
	"time"
)

const dbHost = "localhost"

var cluster *gocql.ClusterConfig
var session *gocql.Session

func main() {
	connect()
	createTable()
	insertRows()
}

func connect() {
	var err error
	// Connect to the cluster.
	cluster = gocql.NewCluster(dbHost)
	cluster.CQLVersion = "3.4.2"
	// Use the same timeout as the Java driver.
	cluster.Timeout = 12 * time.Second

	// Create the session.
	session, err = cluster.CreateSession()
	if err != nil {
		panic(err)
	}
	log.Printf("connected to cluster")
}

func createTable() {
	if err := session.Query("CREATE KEYSPACE IF NOT EXISTS test_float").Exec(); err != nil {
		log.Fatal(err)
	}

	if err := session.Query(`DROP TABLE IF EXISTS test_float.accounts`).Exec(); err != nil {
		log.Fatal(err)
	}

	if err := session.Query(`CREATE TABLE test_float.accounts (id INT PRIMARY KEY, balance DOUBLE, out_locked TEXT)
		WITH transactions = { 'enabled' : true }`).Exec(); err != nil {
		log.Fatal(err)
	}
	log.Println("Created table test_float.accounts")
}

func insertRows() {
	const initialBalance = 200.0
	batch := session.NewBatch(gocql.LoggedBatch)
	for i := 0; i < 5; i++ {
		accNo := i
		batch.Query(`INSERT INTO test_bank.accounts (id, balance) VALUES(?, ?)`, accNo, initialBalance)
	}
	if err := session.ExecuteBatch(batch); err != nil {
		log.Fatal(err)
	}

	log.Println("Inserted test rows into test_float.accounts")
}
```

### What did you see instead?
I get the following error:
`can not marshal float64 into bigint`

**Comment by Zariel** [comment] 2019-12-18 14:45
Try using

const initialBallance float64 = 200.0

**Comment by Ekliptor** [comment] 2019-12-18 15:07
same error with float64 (and float32) during initialBalance declaration

**Comment by OlegLoginov** [comment] 2019-12-19 19:03
What GO version do you use?

Unfortunately I cannot reproduce the issue with the latest YB & gocql.
GO version = 1.13.4
```
19:01 ~/code/go/src/test $ go version
go version go1.13.4 linux/amd64
19:02 ~/code/go/src/test $ go run ./test.go 
2019/12/19 19:02:31 connected to cluster
2019/12/19 19:02:33 Created table test_float.accounts
2019/12/19 19:02:33 Inserted test rows into test_float.accounts
19:02 ~/code/go/src/test $
```

**Comment by Ekliptor** [comment] 2019-12-20 05:19
it is indeed working with `go version go1.13.5`
Previously i had version `go1.13.1` and got the error above. Thx!

**Comment by OlegLoginov** [comment] 2019-12-24 18:38
The problem is resolved in the latest GO versions. So, let's close the issue.

**Closed** 2019-12-24 19:26 UTC
