### ISSUE TITLE
Query timestamp resolution

### ISSUE THREAD

**Issue by karapas** [gocql/gocql#800] opened 2016-10-06 21:55 UTC
Hi folks,

We are using the latest gocql release with Cassandra 3.7.0 ([cqlsh 5.0.1 | Cassandra 3.7.0 | CQL spec 3.4.2 | Native protocol v4]). We noticed some strange behavior where some writes would be lost, even though it is not intended by our application. 

We tracked down the issue and it was because a write, say A, would have a conflicting timestamp with another write, say B (both write update the same row in a table). B is issued right after A, but due to the lexicographical ordering that Cassandra uses for breaking timestamp ties, write A wins over B, thus making the most recent write B to never be applied (contrary to what our application is expecting).

The problem is exhibited when using the default behavior of gocql choosing the timestamps on the client-side (defaultTimestamp set to true), or even when having our code to set manually the timestamp (using the WithTimestamp() function). In both cases we can see that the timestamps have the correct microsecond accuracy and written as such to the framer object using "f.writeLong(ts)" (function writeQueryParams() in frame.go). And at that point, the two writes, A and B, have (as expected) different microsecond accuracy. So they shouldn't conflict, but they eventually do, as if something along the way reduces the accuracy of the two timestamps, which makes them collide.

The problem disappears completely, when using "USING TIMESTAMP" in the query itself, or when letting the timestamps be chosen on the server side. 

NOTE: The behavior could only be reproduced when our Go application and Cassandra were running on the same machine (early development environment) which allowed the two conflicting, sequential writes to be executed at the "same time" when considered with reduced, less-than-microsecond accuracy.

NOTE2: I honestly have no idea if this a gocql driver issue, or a Cassandra issue.

**Comment by martin-sucha** [comment] 2021-12-22 14:41
Based on the description this seems to not be an issue on gocql side, because of:

> In both cases we can see that the timestamps have the correct microsecond accuracy and written as such to the framer object using "f.writeLong(ts)" (function writeQueryParams() in frame.go). And at that point, the two writes, A and B, have (as expected) different microsecond accuracy.

Since this issue is open very long, I'm closing it. Please reopen if you can reproduce with latest gocql and Cassandra version.

**Closed by martin-sucha** 2021-12-22 14:41 UTC
