### ISSUE TITLE
when drop a column, select * got panic

### ISSUE THREAD

**Issue by btfak** [gocql/gocql#1055] opened 2018-02-04 06:58 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.9

### What version of Gocql are you using?
https://github.com/gocql/gocql/tree/1762cce65eafd098045e30ef2b7df2c289740971

### What did you do?
drop a column of a table

I use select * in my code, cassandra has 5 nodes, the table has million records.
```
iter := Cassandra.Query("SELECT * FROM message WHERE id IN ?", messageIDs).Iter()
	for {
		row := make(map[string]interface{})
		if !iter.MapScan(row) {
			break
		}
       }
```

### What did you expect to see?
select still ok

### What did you see instead?

a panic.
panic: not enough bytes in buffer to read int require 4 got 
github.com/gocql/gocql.(*framer).readInt() 
github.com/gocql/gocql/frame.go 1603
github.com/gocql/gocql/frame.go 1677
github.com/gocql/gocql/session.go 1193
github.com/gocql/gocql/session.go 1232
github.com/gocql/gocql/helper.go 318

---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by Zariel** [comment] 2018-02-04 09:51
Does it reproduce on latest master?

**Comment by Zariel** [comment] 2018-02-04 12:01
closing as duplicate of #1056 as its the same issue

**Closed by Zariel** 2018-02-04 12:01 UTC
